---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/web115/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R labs $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH